### ISSUE TITLE
Close button does not reflect Theme's tintColor

### ISSUE THREAD

**Issue by warpling** [themonetizr/The-Monetizr-SDK#1]
![img_6707](https://user-images.githubusercontent.com/220240/31362284-6fc4a66e-ad0c-11e7-94e9-fd71a8691286.jpg)

When the ProductViewNavigationController loads the color of the 'X' appears to match the tintColor before quickly changing to white.

**Comment by armandsavotins** [comment]
Fixed in 2740ebcc5494fafc48ddfc367025554e0a694314
