### ISSUE TITLE
Cancelling Pay shouldn't dismiss Product View Controller

### ISSUE THREAD

**Issue by warpling** [themonetizr/The-Monetizr-SDK#11]
I've had a few people attempt to cancel Pay (maybe to change sizing, etc) and get confused when the product view dismisses. It makes sense to dismiss this view upon checkout success but perhaps upon cancel or failure it should not.

**Comment by armandsavotins** [comment]
Should check status in Shopify’s Mobile Buy SDK https://github.com/Shopify/mobile-buy-sdk-ios/blob/09bfedd034e44eb719cfb70842d2c1ec8485d8b5/Mobile%20Buy%20SDK/Mobile%20Buy%20SDK/Payment%20Providers/BUYApplePayPaymentProvider.m#L267

**Comment by armandsavotins** [comment]
It can be achieved in Mobile BUY SDK BUYApplePayPaymentProvider.m
Call [self.delegate paymentProviderWantsControllerDismissed:self]; only if BUYStatusFailed

**Comment by warpling** [comment]
Looks like it's working to me!
