### ISSUE TITLE
Add option to hide status bar

### ISSUE THREAD

**Issue by warpling** [themonetizr/The-Monetizr-SDK#13]
Most games don't show a status bar. Often an entire application is configured to either show or hide status bars but sometimes we use "View controller-based status bar appearance" to change the status bar appearance on the fly based on the VC and other factors.

It'd be nice to be able to add an option that can be modified to decide whether to show/hide the status bar. In some cases it can be important so show the status bar after the fact (in my case I show the status bar to VoiceOver users) so ideally this option can be changed later and will update all necessary views. 🙌

**Comment by armandsavotins** [comment]
e80719371a3004a7000c4467b85ebeb3bba7bd21 - added hidesStatusBar property in theme.

**Comment by warpling** [comment]
Perfect.
