### ISSUE TITLE
Design suggestion to clarify order details before checkout

### ISSUE THREAD

**Issue by warpling** [themonetizr/The-Monetizr-SDK#14]
Some people do not notice default product options and expect to choose a size/quantity etc upon checkout. Since people may be reading the description before choosing the payment option it would help to give proximity of the selected item to checkout. This still allows for a default and would probably reduce support emails related to updating sizing, etc ;)

![merch options redesign idea](https://user-images.githubusercontent.com/220240/32249772-6c5c2e2e-be47-11e7-9f15-0611473d9d04.png)

**Comment by armandsavotins** [comment]
Redesigned in 8f4d4efd2efe1b5ffa671f2227ab2fce132abc43

**Comment by armandsavotins** [comment]
and here 8c12b000496a9e889d178db37fa37c8527b1cde1

**Comment by warpling** [comment]
This looks fantastic! I think this'll greatly decrease the number of incorrect orders. On both themes it is a bit hard to tell it apart from the background. What do you think of using a UIBlurEffect (light on the light theme, dark on the dark theme) for the selection bar? Could look sharp when scrolling and help with the sense of hierarchy the payment buttons already have.

**Comment by armandsavotins** [comment]
Yes probably ActionableFooterView could be transparent with UIBlurEffect. I will let @skorovs to decide.

**Comment by armandsavotins** [comment]
UIBlurEffect on variant selection view can be found here - 62829770fdf53a8cd461c323527f1db5b89d3bb7

**Comment by warpling** [comment]
This looks great Armands!
