### ISSUE TITLE
Idea for improving close button?

### ISSUE THREAD

**Issue by warpling** [themonetizr/The-Monetizr-SDK#15]
I noticed that the close button is very difficult to reach on the iPhone X being in the top left corner and can be quite difficult to see on certain product images. Perhaps it'd help to take a page from what Apple has done in the iOS 11 App Store to visually distinguish it more and place it in a slightly more comfortable to reach corner with a larger touch area? To be fair they also allow the gesture of pulling the content to close the view (similar to Blackbox's store view). :)

Surprise surprise, the circle size is 44pt (smallest recommended tap target size) and it looks like they're using a UIBlurEffect for the circle and the effect/color switches depending on the underlying art/section. The 'x' appears to have rounded end caps.

<img width="826" alt="screen shot 2017-11-07 at 2 44 20 pm" src="https://user-images.githubusercontent.com/220240/32521934-2e46bd92-c3ca-11e7-966d-64235276cb53.png">

**Comment by warpling** [comment]
At the very least an enlarged touch target would help with the current 'X' button!

**Comment by skorovs** [comment]
@warpling Ok, we will look into it!

**Comment by armandsavotins** [comment]
Enlarged touch target for the current 'X' button! - ab25832dfd3c0f91ffae3d727b6bc0f95d95446a

**Comment by armandsavotins** [comment]
One more update "X" button changed from custom to UIBarButtonSystemItemStop - c06dcbacc7374107fcd5367e54cc6328efe43c42 I think this will be event better

**Comment by armandsavotins** [comment]
I suggest not to implement App Store close button. I agree we could implement  "pull to close" gesture.

**Comment by warpling** [comment]
143a71c fixes the accessibility label on this new icon. Great call using the system icon.
Once there's a gesture to make closing less painful on taller devices this is good to close!

**Comment by armandsavotins** [comment]
9f0994ac35f7038ec1b8552aadd1598814a4b571 Dismiss ProductView by pulling

**Comment by skorovs** [comment]
We will explore better ways to enable Pull to close. Thanks for the idea!
