### ISSUE TITLE
Product image header doesn't size to fit height of images

### ISSUE THREAD

**Issue by warpling** [themonetizr/The-Monetizr-SDK#2]
![img_6708](https://user-images.githubusercontent.com/220240/31362363-f576a398-ad0c-11e7-95aa-318104e965fc.jpg)

If the image area sized itself to be the height of the tallest image it'd allow more information to be seen before scrolling.

**Comment by armandsavotins** [comment]
Fixed in 2740ebcc5494fafc48ddfc367025554e0a694314

**Comment by warpling** [comment]
I'm not sure I understand. Would it be possible to add something like this with auto-layout?

**Comment by armandsavotins** [comment]
ProductViewHeader is designed to be a square. Probably because images can be with different aspect ratios and ProductViewHeader should handle paging between them. Also in the latest code images are Filling the area.

**Comment by warpling** [comment]
This looks great now at least in my opinion in use case! I'd close this if it works alright for others.

**Comment by warpling** [comment]
LGTM on iPhone X, 7, and 5s.
