### ISSUE TITLE
Swift 4.2 Triggering new warnings in SDK

### ISSUE THREAD

**Issue by warpling** [themonetizr/The-Monetizr-SDK#23]
`Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior`

It seems [the recommended solution](https://stackoverflow.com/a/21577823/522498) is to mark those ivar references with `self->iVarName` or change them to properties. Should be a quick fix to silence these warnings!

**Comment by armandsavotins** [comment]
@warpling  do you have such warning in Monetizr.m ?

**Comment by armandsavotins** [comment]
Does this 8d9cd27423b8b67e14bca166fb3bbf3ed1da6842 help?

**Comment by warpling** [comment]
This helps! I turned of my warning silencing of the SDK's files and still found the following:

---
**CheckoutViewController**
* `-[PKPaymentAuthorizationViewControllerDelegate paymentAuthorizationViewController:didSelectShippingAddress:completion:]` is deprecated
* `ABRecordRef` is deprecated
* `openURL:` is deprecated

**Mobile-Buy-SDK**
* Continues to issue deprecation warnings but I'm told this library will be dropped or updated soon?

**Comment by armandsavotins** [comment]
paymentAuthorizationViewController:didSelectShippingAddress:completion:] is deprecated
ABRecordRef is deprecated

It looks like these warnings can be fixed migrating from AddressBookUI framework to ContactsUI Framework but there is dependency from _BUYApplePayAuthorizationDelegate_ which is part of **Mobile-Buy-SDK**

**Comment by armandsavotins** [comment]
openURL: is deprecated warning should be gone with 3fb1340990b67e8cb9903e809443d59f7784f2fe

**Comment by warpling** [comment]
Ah okay gotcha. Thanks for looking into these! What’s the ETA on switching dependencies? More than the warnings it makes me uncomfortable to include outdated payment SDKs with potential security vulnerabilities.

**Comment by armandsavotins** [comment]
> What’s the ETA on switching dependencies?

I guess this question should go to @skorovs
