### ISSUE TITLE
Loading View should not modify client apps view hierarchy

### ISSUE THREAD

**Issue by warpling** [themonetizr/The-Monetizr-SDK#7]
`addLoadingView`/`removeLoadingView` are added to the client app's `rootViewController`'s subviews and rely on an arbitrary tag to be successful added/removed. There are many safer ways to display a loading indicator without using tags or modifying the client app's view hierarchy.

Consider instead presenting a ViewController with an activity indicator or better yet **present `ProductViewController` immediately with a activity indicator in it.**

**Comment by armandsavotins** [comment]
8f59ee4f9bc731edaa1188d7aef02b85dab906a3

Loading view removed - use completion blocks to create own loading indicator if needed

**Comment by warpling** [comment]
Having the client provide the loading view might be problematic since the completion handler is called after the VC is finished presenting so if it takes a half-second to animate into view then the loading indicator would be visible _until_ the VC finished transitioning.

It'd be great if we could get the productVC to animate in instantly and then load whatever it is it needs to load once the view is already visible (Imagine Facebook or Instagram with placeholder images, etc). :)
